---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.3.9-jdk-8}

inputs:
  - name: source-code
  - name: pipeline
outputs:
  - name: build
  
run:
  path: pipeline/tasks/maven-build.sh
