---
platform: linux
image_resource:
  type: docker-image
  source: {repository: concourse/buildroot, tag: curl}

inputs:
  - name: version
  - name: build
outputs:
  - name: release-candidate

run:
  path: pipeline/tasks/promote-build.sh
